site_name: GiftLink
repo_url: https://github.com/JhonataAugust0/giftlink
repo_name: JhonataAugust0/giftlink
edit_uri: tree/master/docs

theme:
  name: material
  language: pt-BR

markdown_extensions:
  - attr_list

extra_css: 
  - stylesheets/extra.css